//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long Id { get; set; }
        public long GoodsId { get; set; }
        public long ClientId { get; set; }
        public long MasterId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
